### ISSUE TITLE
install.sh error - cannot access archive 

### ISSUE THREAD

**Issue by sgreadly** [techcoder20/MacOSBigSurThemeConverter#3]
Hi,

Just testing this out on my 3B+, but the installer keeps failing around this spot. I tried ./uninstall.sh and to re- install.sh, but same error. 

`$ uname -a
Linux hop3 5.4.83-v7+ #1379 SMP Mon Dec 14 13:08:57 GMT 2020 armv7l GNU/Linux`

> dpkg: error: cannot access archive '/home/pi/.local/share/MacOSBigSurThemeConverter/assets/xfce4-panel-profiles_1.0.10-1_armhf.deb': No such file or directory
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> The following package was automatically installed and is no longer required:
>   lxplug-volume
> Use 'sudo apt autoremove' to remove it.
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> cp: cannot stat '/home/pi/.local/share/MacOSBigSurThemeConverter/assets> /MacOSBigSurThemeConverterAutostart.desktop': No such file or directory
> cp: cannot stat '/home/pi/.local/share/MacOSBigSurThemeConverter/assets/Icons/*': No such file or directory
> cp: cannot stat '/home/pi/.local/share/MacOSBigSurThemeConverter/assets/DesktopFiles/*': No such file or directory
> cp: cannot stat '/home/pi/.local/share/MacOSBigSurThemeConverter/assets/MacOSBigSurLight/mcOS-BS-White-Stock': > No such file or directory
> cp: cannot stat '/home/pi/.local/share/MacOSBigSurThemeConverter/assets/MacOSBigSurDark/mcOS-BS-Black-Stock': No such file or directory
> rm: cannot remove '/home/pi/.config/plank': No such file or directory
> cp: cannot stat '/home/pi/.local/share/MacOSBigSurThemeConverter/assets/plank': No such file or directory
> chmod: cannot access '/home/pi/.local/share/MacOSBigSurThemeConverter/uninstall.sh': No such file or directory
> chmod: cannot access '/home/pi/.local/share/MacOSBigSurThemeConverter/MacOSBigSurThemeConverter.sh': No such file or directory
> chmod: cannot access '/home/pi/.local/share/MacOSBigSurThemeConverter/assets> /MacOSBigSurThemeConverterAutostart.sh': No such file or directory
> ./install.sh: line 204: /home/pi/.local/share/MacOSBigSurThemeConverter/MacOSBigSurThemeConverter.sh: No such file or directory

**Comment by techcoder20** [comment]
Hello @sgreadly ,
This is happening because the converter files are not getting copied to ~/.local/share/MacOSBigSurThemeConverter. I have updated the script so that if the files failed to get copied it will stop the script so can u clone the git repo again and check if the script stops at that point. It should print the error `Unable to copy converter files to ~/.local/share/MacOSBigSurThemeConverter` These commands should do it 

```
rm -r ~/MacOSBigSurThemeConverter
git clone https://github.com/techcoder20/MacOSBigSurThemeConverter.git
sudo chmod +x ~/MacOSBigSurThemeConverter/install.sh
~/MacOSBigSurThemeConverter/install.sh
```

**Comment by sgreadly** [comment]
Thanks, 

Works now, and without errors. 

I think I see the main issue that lead to the above. I cloned mine to ~/Downloads/ instead of ~/ . Your script seems to want it to be in ~/ . Is there any way to have the destination not fixed ?

**Comment by techcoder20** [comment]
> Thanks,
> 
> Works now, and without errors.
> 
> I think I see the main issue that lead to the above. I cloned mine to ~/Downloads/ instead of ~/ . Your script seems to want it to be in ~/ . Is there any way to have the destination not fixed ?

i will look into that :)
